baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Kurtis Adams"
        tagline = "Comp Sci Student"
        location = "USF"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/kmadams50/"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "https://stackoverflow.com/users/13886488/randomdebugerror?tab=profile"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/RandomDebugError"
            title = "GitHub"
        [[params.social.list]]
            icon = "far fa-file"
            url = "https://www.dropbox.com/s/r6p0r72o80mihmf/Adams_Resume.pdf?dl=0"
            title = "CV"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I am a University of South Florida Computer Science student that is cuurently working for Sofwerx as a Cyber Secutity & Engineering Intern. I am a United States Navy Verteran that worked in the Cryptologic field."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Cyber Security & Engineering Intern"
            dates = "AUG 2020 - *Present*"
            company = "Sofwerx"
            url = "https://sofwerx.org/"
            details = "Finding creative solutions for problems for the modern day special operations warfighter in the fields of facial recognition and machine learning."
        [[params.experience.list]]
            position = "Engineering Test Technician"
            dates = "JUN 2017 - MAR 2018"
            company = "Sensor Systems LLC."
            details = "Inspected and maintained test objects at all test locations.  Assembled and tested routine circuitry (breadboard) and full prototype models and assisted in the development and improvement of test techniques and associated documentation Also Maintained records of repairs, calibrations and tests."
        [[params.experience.list]]
            position = "CTR2"
            dates = "FEB 2012 - APR 2015"
            company = "United States Navy"
            details = "Supervised the operations of Radio Direction Finding equipment while stationed onboard the USS Farragut. Oversaw the dissemination of over 3000 time sensitive products, ensuring accurate reporting to consumers. Demonstrated reliability acting as Top Secret information custodian resulting in zero incidents. Trained two teams of USS Farragut crew and various members of other naval vessels on operation and troubleshooting of 13 million dollar Signals Intelligence system."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        
        [[params.education.list]]
            degree = "B.S. in Computer Science"
            college = "University of South Florida"
            dates = "2018 - 2022"
        [[params.education.list]]
            degree = "A.S. in Electronics Engineering Technology"
            college = "Hillsborough Community College"
            dates = "2015 - 2017"

    

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "None at the moment"
            url = "#"
            description = "All current projects have been are work related."



    # Skill section
    [params.skill]
        title = "Language Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "C++"
            skillrating = 80
        [[params.skill.list]]
            skill = "C"
            skillrating = 70
        [[params.skill.list]]
            skill = "Python"
            skillrating = 60
        [[params.skill.list]]
            skill = "C#, Java"
            skillrating = 50
        [[params.skill.list]]
            skill = "HTML, CSS"
            skillrating = 45

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Diving"
        [[params.hobby.list]]
            hobby = "Kayaking"
        [[params.hobby.list]]
            hobby = "Fishing"
        [[params.hobby.list]]
            hobby = "Hiking"
       